### Get movies
GET http://localhost:3000/movies

### Get movie by id
GET http://localhost:3000/movies/a22ec36a-84bb-11ee-b43c-509a4c43f702

### Get movies by genre
GET http://localhost:3000/movies?genre=fantasy

### Crate movie
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "Sound of Freedom",
  "year": 2023,
  "director": "Alejandro Monteverde",
  "duration": 131,
  "poster": "https://upload.wikimedia.org/wikipedia/en/0/0f/The_Sound_of_Freedom_Poster.jpg",
  "genres": ["Action", "Drama"]
}

### Update movie
PATCH http://localhost:3000/movies/57c38c3a-67bd-11ee-b095-509a4c43f702
Content-Type: application/json

{
  "year": 1994
}

### Delete movie
DELETE http://localhost:3000/movies/e7859c23-6c72-11ee-8bef-509a4c43f702